version: '3.7'
name: albion-gamble

services:

  sveltekit:
    build: ./sveltekit
    ports:
      - "3000:3000"

  caddy:
    build: ./caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=e88qeDadRXr1b3s8RuFKfQAInwxBorD9hs2Qn69C
      - ZONE=albiongamble.win
      - SUBDOMAIN=nig
      - PROXIED=false

volumes:
  caddy_data:
  caddy_config: